
services:
  frontend:
    build: .
    container_name: myweb_frontend
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm run start"

  api:
    build: .
    container_name: myweb_api
    ports:
      - "4080:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    command: sh -c " npm run start"
    