services:
  frontend:
    build: .
    container_name: myweb_frontend
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always

  api:
    build: .
    container_name: myweb_api
    ports:
      - "4080:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    # In prod-like mode we "build/start", not "dev"
    command: npm run start
    restart: always